// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: pb/svc/db/db.proto

package db

import (
	device "github.com/byeol-i/battery-level-checker/pb/unit/device"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignUpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *SignUpReq) Reset() {
	*x = SignUpReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_db_db_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignUpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpReq) ProtoMessage() {}

func (x *SignUpReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_db_db_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpReq.ProtoReflect.Descriptor instead.
func (*SignUpReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_db_db_proto_rawDescGZIP(), []int{0}
}

func (x *SignUpReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type SignUpRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *SignUpRes) Reset() {
	*x = SignUpRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_db_db_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignUpRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpRes) ProtoMessage() {}

func (x *SignUpRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_db_db_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpRes.ProtoReflect.Descriptor instead.
func (*SignUpRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_db_db_proto_rawDescGZIP(), []int{1}
}

func (x *SignUpRes) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *SignUpRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AddDeviceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Device *device.Device `protobuf:"bytes,1,opt,name=Device,proto3" json:"Device,omitempty"`
}

func (x *AddDeviceReq) Reset() {
	*x = AddDeviceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_db_db_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDeviceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDeviceReq) ProtoMessage() {}

func (x *AddDeviceReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_db_db_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDeviceReq.ProtoReflect.Descriptor instead.
func (*AddDeviceReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_db_db_proto_rawDescGZIP(), []int{2}
}

func (x *AddDeviceReq) GetDevice() *device.Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type AddDeviceRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AddDeviceRes) Reset() {
	*x = AddDeviceRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_db_db_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDeviceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDeviceRes) ProtoMessage() {}

func (x *AddDeviceRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_db_db_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDeviceRes.ProtoReflect.Descriptor instead.
func (*AddDeviceRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_db_db_proto_rawDescGZIP(), []int{3}
}

func (x *AddDeviceRes) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AddDeviceRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetDevicesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *GetDevicesReq) Reset() {
	*x = GetDevicesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_db_db_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDevicesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesReq) ProtoMessage() {}

func (x *GetDevicesReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_db_db_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesReq.ProtoReflect.Descriptor instead.
func (*GetDevicesReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_db_db_proto_rawDescGZIP(), []int{4}
}

func (x *GetDevicesReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type GetDevicesRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Devices []*device.Device `protobuf:"bytes,1,rep,name=Devices,proto3" json:"Devices,omitempty"`
}

func (x *GetDevicesRes) Reset() {
	*x = GetDevicesRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_db_db_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDevicesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesRes) ProtoMessage() {}

func (x *GetDevicesRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_db_db_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesRes.ProtoReflect.Descriptor instead.
func (*GetDevicesRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_db_db_proto_rawDescGZIP(), []int{5}
}

func (x *GetDevicesRes) GetDevices() []*device.Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type RemoveDeviceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveDeviceReq) Reset() {
	*x = RemoveDeviceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_db_db_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveDeviceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDeviceReq) ProtoMessage() {}

func (x *RemoveDeviceReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_db_db_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDeviceReq.ProtoReflect.Descriptor instead.
func (*RemoveDeviceReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_db_db_proto_rawDescGZIP(), []int{6}
}

type RemoveDeviceRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveDeviceRes) Reset() {
	*x = RemoveDeviceRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_db_db_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveDeviceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDeviceRes) ProtoMessage() {}

func (x *RemoveDeviceRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_db_db_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDeviceRes.ProtoReflect.Descriptor instead.
func (*RemoveDeviceRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_db_db_proto_rawDescGZIP(), []int{7}
}

var File_pb_svc_db_db_proto protoreflect.FileDescriptor

var file_pb_svc_db_db_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x62, 0x2f, 0x73, 0x76, 0x63, 0x2f, 0x64, 0x62, 0x2f, 0x64, 0x62, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x64, 0x62, 0x1a,
	0x1b, 0x70, 0x62, 0x2f, 0x75, 0x6e, 0x69, 0x74, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1d, 0x0a, 0x09,
	0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x39, 0x0a, 0x09, 0x53,
	0x69, 0x67, 0x6e, 0x55, 0x70, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x3e, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x2e, 0x0a, 0x06, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x75, 0x6e, 0x69, 0x74,
	0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x06,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x22, 0x3c, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x21, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x41, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x07, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x75,
	0x6e, 0x69, 0x74, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x07, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x11, 0x0a, 0x0f, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x22, 0x11, 0x0a,
	0x0f, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x32, 0x83, 0x02, 0x0a, 0x02, 0x44, 0x42, 0x12, 0x34, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x55,
	0x70, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x64, 0x62, 0x2e, 0x53, 0x69,
	0x67, 0x6e, 0x55, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63,
	0x2e, 0x64, 0x62, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x52, 0x65, 0x73, 0x12, 0x3d, 0x0a,
	0x09, 0x41, 0x64, 0x64, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e,
	0x73, 0x76, 0x63, 0x2e, 0x64, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x64, 0x62, 0x2e,
	0x41, 0x64, 0x64, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x12, 0x46, 0x0a, 0x0c,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x2e, 0x70,
	0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x64, 0x62, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76,
	0x63, 0x2e, 0x64, 0x62, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x12, 0x40, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x64, 0x62, 0x2e, 0x47,
	0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70,
	0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x64, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x79, 0x65, 0x6f, 0x6c, 0x2d, 0x69, 0x2f, 0x62, 0x61, 0x74,
	0x74, 0x65, 0x72, 0x79, 0x2d, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2d, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x76, 0x63, 0x2f, 0x64, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_svc_db_db_proto_rawDescOnce sync.Once
	file_pb_svc_db_db_proto_rawDescData = file_pb_svc_db_db_proto_rawDesc
)

func file_pb_svc_db_db_proto_rawDescGZIP() []byte {
	file_pb_svc_db_db_proto_rawDescOnce.Do(func() {
		file_pb_svc_db_db_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_svc_db_db_proto_rawDescData)
	})
	return file_pb_svc_db_db_proto_rawDescData
}

var file_pb_svc_db_db_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pb_svc_db_db_proto_goTypes = []interface{}{
	(*SignUpReq)(nil),       // 0: pb.svc.db.SignUpReq
	(*SignUpRes)(nil),       // 1: pb.svc.db.SignUpRes
	(*AddDeviceReq)(nil),    // 2: pb.svc.db.AddDeviceReq
	(*AddDeviceRes)(nil),    // 3: pb.svc.db.AddDeviceRes
	(*GetDevicesReq)(nil),   // 4: pb.svc.db.GetDevicesReq
	(*GetDevicesRes)(nil),   // 5: pb.svc.db.GetDevicesRes
	(*RemoveDeviceReq)(nil), // 6: pb.svc.db.RemoveDeviceReq
	(*RemoveDeviceRes)(nil), // 7: pb.svc.db.RemoveDeviceRes
	(*device.Device)(nil),   // 8: pb.unit.device.Device
}
var file_pb_svc_db_db_proto_depIdxs = []int32{
	8, // 0: pb.svc.db.AddDeviceReq.Device:type_name -> pb.unit.device.Device
	8, // 1: pb.svc.db.GetDevicesRes.Devices:type_name -> pb.unit.device.Device
	0, // 2: pb.svc.db.DB.SignUp:input_type -> pb.svc.db.SignUpReq
	2, // 3: pb.svc.db.DB.AddDevice:input_type -> pb.svc.db.AddDeviceReq
	6, // 4: pb.svc.db.DB.RemoveDevice:input_type -> pb.svc.db.RemoveDeviceReq
	4, // 5: pb.svc.db.DB.GetDevices:input_type -> pb.svc.db.GetDevicesReq
	1, // 6: pb.svc.db.DB.SignUp:output_type -> pb.svc.db.SignUpRes
	3, // 7: pb.svc.db.DB.AddDevice:output_type -> pb.svc.db.AddDeviceRes
	7, // 8: pb.svc.db.DB.RemoveDevice:output_type -> pb.svc.db.RemoveDeviceRes
	5, // 9: pb.svc.db.DB.GetDevices:output_type -> pb.svc.db.GetDevicesRes
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_svc_db_db_proto_init() }
func file_pb_svc_db_db_proto_init() {
	if File_pb_svc_db_db_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_svc_db_db_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignUpReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_db_db_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignUpRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_db_db_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDeviceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_db_db_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDeviceRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_db_db_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDevicesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_db_db_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDevicesRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_db_db_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveDeviceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_db_db_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveDeviceRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_svc_db_db_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_svc_db_db_proto_goTypes,
		DependencyIndexes: file_pb_svc_db_db_proto_depIdxs,
		MessageInfos:      file_pb_svc_db_db_proto_msgTypes,
	}.Build()
	File_pb_svc_db_db_proto = out.File
	file_pb_svc_db_db_proto_rawDesc = nil
	file_pb_svc_db_db_proto_goTypes = nil
	file_pb_svc_db_db_proto_depIdxs = nil
}
