FROM postgres:11-alpine

ENV LANG C.UTF-8

COPY ./cmd/db/primary/init.sql /docker-entrypoint-initdb.d/init.sql

COPY ./cmd/db/primary/alter_systems.sql /docker-entrypoint-initdb.d/alter_systems.sql

COPY ./cmd/db/primary/pghba.sh /docker-entrypoint-initdb.d/pghba.sh