// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: pb/svc/firebase/firebase.proto

package firebase

import (
	common "github.com/byeol-i/battery-level-checker/pb/unit/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyIdTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *VerifyIdTokenReq) Reset() {
	*x = VerifyIdTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_firebase_firebase_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyIdTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyIdTokenReq) ProtoMessage() {}

func (x *VerifyIdTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_firebase_firebase_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyIdTokenReq.ProtoReflect.Descriptor instead.
func (*VerifyIdTokenReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_firebase_firebase_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyIdTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerifyIdTokenRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *common.ReturnMsg `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *VerifyIdTokenRes) Reset() {
	*x = VerifyIdTokenRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_firebase_firebase_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyIdTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyIdTokenRes) ProtoMessage() {}

func (x *VerifyIdTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_firebase_firebase_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyIdTokenRes.ProtoReflect.Descriptor instead.
func (*VerifyIdTokenRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_firebase_firebase_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyIdTokenRes) GetResult() *common.ReturnMsg {
	if x != nil {
		return x.Result
	}
	return nil
}

type CreateCustomTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *CreateCustomTokenReq) Reset() {
	*x = CreateCustomTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_firebase_firebase_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCustomTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomTokenReq) ProtoMessage() {}

func (x *CreateCustomTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_firebase_firebase_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomTokenReq.ProtoReflect.Descriptor instead.
func (*CreateCustomTokenReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_firebase_firebase_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCustomTokenReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type CreateCustomTokenRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CreateCustomTokenRes) Reset() {
	*x = CreateCustomTokenRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_firebase_firebase_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCustomTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomTokenRes) ProtoMessage() {}

func (x *CreateCustomTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_firebase_firebase_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomTokenRes.ProtoReflect.Descriptor instead.
func (*CreateCustomTokenRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_firebase_firebase_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCustomTokenRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateCustomTokenRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *GetUserReq) Reset() {
	*x = GetUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_firebase_firebase_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReq) ProtoMessage() {}

func (x *GetUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_firebase_firebase_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReq.ProtoReflect.Descriptor instead.
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_firebase_firebase_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type GetUserRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *common.ReturnMsg `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *GetUserRes) Reset() {
	*x = GetUserRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_firebase_firebase_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRes) ProtoMessage() {}

func (x *GetUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_firebase_firebase_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRes.ProtoReflect.Descriptor instead.
func (*GetUserRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_firebase_firebase_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserRes) GetResult() *common.ReturnMsg {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetUserIdByIdTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *GetUserIdByIdTokenReq) Reset() {
	*x = GetUserIdByIdTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_firebase_firebase_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserIdByIdTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserIdByIdTokenReq) ProtoMessage() {}

func (x *GetUserIdByIdTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_firebase_firebase_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserIdByIdTokenReq.ProtoReflect.Descriptor instead.
func (*GetUserIdByIdTokenReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_firebase_firebase_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserIdByIdTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetUserIdByIdTokenRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *common.ReturnMsg `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *GetUserIdByIdTokenRes) Reset() {
	*x = GetUserIdByIdTokenRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_firebase_firebase_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserIdByIdTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserIdByIdTokenRes) ProtoMessage() {}

func (x *GetUserIdByIdTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_firebase_firebase_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserIdByIdTokenRes.ProtoReflect.Descriptor instead.
func (*GetUserIdByIdTokenRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_firebase_firebase_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserIdByIdTokenRes) GetResult() *common.ReturnMsg {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_pb_svc_firebase_firebase_proto protoreflect.FileDescriptor

var file_pb_svc_firebase_firebase_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x62, 0x2f, 0x73, 0x76, 0x63, 0x2f, 0x66, 0x69, 0x72, 0x65, 0x62, 0x61, 0x73,
	0x65, 0x2f, 0x66, 0x69, 0x72, 0x65, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x66, 0x69, 0x72, 0x65, 0x62, 0x61, 0x73,
	0x65, 0x1a, 0x18, 0x70, 0x62, 0x2f, 0x75, 0x6e, 0x69, 0x74, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x10, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x45, 0x0a, 0x10, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49,
	0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x75,
	0x6e, 0x69, 0x74, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x4d, 0x73, 0x67, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x28, 0x0a, 0x14,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x42, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x1e, 0x0a, 0x0a, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x3f, 0x0a, 0x0a, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x75, 0x6e,
	0x69, 0x74, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e,
	0x4d, 0x73, 0x67, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x2d, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x42, 0x79, 0x49, 0x64, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x4a, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x42, 0x79, 0x49, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x52, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x4d, 0x73, 0x67, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0xef, 0x02, 0x0a, 0x08, 0x46, 0x69, 0x72, 0x65, 0x62,
	0x61, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1b,
	0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x66, 0x69, 0x72, 0x65, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x70, 0x62,
	0x2e, 0x73, 0x76, 0x63, 0x2e, 0x66, 0x69, 0x72, 0x65, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x61, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x25, 0x2e,
	0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x66, 0x69, 0x72, 0x65, 0x62, 0x61, 0x73, 0x65, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x71, 0x1a, 0x25, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x66, 0x69,
	0x72, 0x65, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x55, 0x0a, 0x0d, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x21, 0x2e, 0x70,
	0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x66, 0x69, 0x72, 0x65, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x1a,
	0x21, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x66, 0x69, 0x72, 0x65, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x73, 0x12, 0x64, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x42,
	0x79, 0x49, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x26, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76,
	0x63, 0x2e, 0x66, 0x69, 0x72, 0x65, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x42, 0x79, 0x49, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71,
	0x1a, 0x26, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x66, 0x69, 0x72, 0x65, 0x62, 0x61,
	0x73, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x42, 0x79, 0x49, 0x64,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x79, 0x65, 0x6f, 0x6c, 0x2d, 0x69, 0x2f, 0x62,
	0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2d, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2d, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x76, 0x63, 0x2f, 0x66, 0x69, 0x72, 0x65,
	0x62, 0x61, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_svc_firebase_firebase_proto_rawDescOnce sync.Once
	file_pb_svc_firebase_firebase_proto_rawDescData = file_pb_svc_firebase_firebase_proto_rawDesc
)

func file_pb_svc_firebase_firebase_proto_rawDescGZIP() []byte {
	file_pb_svc_firebase_firebase_proto_rawDescOnce.Do(func() {
		file_pb_svc_firebase_firebase_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_svc_firebase_firebase_proto_rawDescData)
	})
	return file_pb_svc_firebase_firebase_proto_rawDescData
}

var file_pb_svc_firebase_firebase_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pb_svc_firebase_firebase_proto_goTypes = []interface{}{
	(*VerifyIdTokenReq)(nil),      // 0: pb.svc.firebase.VerifyIdTokenReq
	(*VerifyIdTokenRes)(nil),      // 1: pb.svc.firebase.VerifyIdTokenRes
	(*CreateCustomTokenReq)(nil),  // 2: pb.svc.firebase.CreateCustomTokenReq
	(*CreateCustomTokenRes)(nil),  // 3: pb.svc.firebase.CreateCustomTokenRes
	(*GetUserReq)(nil),            // 4: pb.svc.firebase.GetUserReq
	(*GetUserRes)(nil),            // 5: pb.svc.firebase.GetUserRes
	(*GetUserIdByIdTokenReq)(nil), // 6: pb.svc.firebase.GetUserIdByIdTokenReq
	(*GetUserIdByIdTokenRes)(nil), // 7: pb.svc.firebase.GetUserIdByIdTokenRes
	(*common.ReturnMsg)(nil),      // 8: pb.unit.common.ReturnMsg
}
var file_pb_svc_firebase_firebase_proto_depIdxs = []int32{
	8, // 0: pb.svc.firebase.VerifyIdTokenRes.result:type_name -> pb.unit.common.ReturnMsg
	8, // 1: pb.svc.firebase.GetUserRes.result:type_name -> pb.unit.common.ReturnMsg
	8, // 2: pb.svc.firebase.GetUserIdByIdTokenRes.result:type_name -> pb.unit.common.ReturnMsg
	4, // 3: pb.svc.firebase.Firebase.GetUser:input_type -> pb.svc.firebase.GetUserReq
	2, // 4: pb.svc.firebase.Firebase.CreateCustomToken:input_type -> pb.svc.firebase.CreateCustomTokenReq
	0, // 5: pb.svc.firebase.Firebase.VerifyIdToken:input_type -> pb.svc.firebase.VerifyIdTokenReq
	6, // 6: pb.svc.firebase.Firebase.GetUserIdByIdToken:input_type -> pb.svc.firebase.GetUserIdByIdTokenReq
	5, // 7: pb.svc.firebase.Firebase.GetUser:output_type -> pb.svc.firebase.GetUserRes
	3, // 8: pb.svc.firebase.Firebase.CreateCustomToken:output_type -> pb.svc.firebase.CreateCustomTokenRes
	1, // 9: pb.svc.firebase.Firebase.VerifyIdToken:output_type -> pb.svc.firebase.VerifyIdTokenRes
	7, // 10: pb.svc.firebase.Firebase.GetUserIdByIdToken:output_type -> pb.svc.firebase.GetUserIdByIdTokenRes
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_svc_firebase_firebase_proto_init() }
func file_pb_svc_firebase_firebase_proto_init() {
	if File_pb_svc_firebase_firebase_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_svc_firebase_firebase_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyIdTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_firebase_firebase_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyIdTokenRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_firebase_firebase_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCustomTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_firebase_firebase_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCustomTokenRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_firebase_firebase_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_firebase_firebase_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_firebase_firebase_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserIdByIdTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_firebase_firebase_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserIdByIdTokenRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_svc_firebase_firebase_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_svc_firebase_firebase_proto_goTypes,
		DependencyIndexes: file_pb_svc_firebase_firebase_proto_depIdxs,
		MessageInfos:      file_pb_svc_firebase_firebase_proto_msgTypes,
	}.Build()
	File_pb_svc_firebase_firebase_proto = out.File
	file_pb_svc_firebase_firebase_proto_rawDesc = nil
	file_pb_svc_firebase_firebase_proto_goTypes = nil
	file_pb_svc_firebase_firebase_proto_depIdxs = nil
}
