// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: pb/svc/consumer/consumer.proto

package consumer

import (
	common "github.com/byeol-i/battery-level-checker/pb/unit/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserDevicesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *GetUserDevicesReq) Reset() {
	*x = GetUserDevicesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_consumer_consumer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserDevicesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDevicesReq) ProtoMessage() {}

func (x *GetUserDevicesReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_consumer_consumer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDevicesReq.ProtoReflect.Descriptor instead.
func (*GetUserDevicesReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_consumer_consumer_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserDevicesReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type GetUserDevicesRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *common.ReturnMsg `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *GetUserDevicesRes) Reset() {
	*x = GetUserDevicesRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_consumer_consumer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserDevicesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDevicesRes) ProtoMessage() {}

func (x *GetUserDevicesRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_consumer_consumer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDevicesRes.ProtoReflect.Descriptor instead.
func (*GetUserDevicesRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_consumer_consumer_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserDevicesRes) GetResult() *common.ReturnMsg {
	if x != nil {
		return x.Result
	}
	return nil
}

type CreateNewMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *CreateNewMsgReq) Reset() {
	*x = CreateNewMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_consumer_consumer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNewMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewMsgReq) ProtoMessage() {}

func (x *CreateNewMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_consumer_consumer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewMsgReq.ProtoReflect.Descriptor instead.
func (*CreateNewMsgReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_consumer_consumer_proto_rawDescGZIP(), []int{2}
}

func (x *CreateNewMsgReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type CreateNewMsgRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateNewMsgRes) Reset() {
	*x = CreateNewMsgRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_consumer_consumer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNewMsgRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewMsgRes) ProtoMessage() {}

func (x *CreateNewMsgRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_consumer_consumer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewMsgRes.ProtoReflect.Descriptor instead.
func (*CreateNewMsgRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_consumer_consumer_proto_rawDescGZIP(), []int{3}
}

type CreateNewTopicReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
}

func (x *CreateNewTopicReq) Reset() {
	*x = CreateNewTopicReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_consumer_consumer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNewTopicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewTopicReq) ProtoMessage() {}

func (x *CreateNewTopicReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_consumer_consumer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewTopicReq.ProtoReflect.Descriptor instead.
func (*CreateNewTopicReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_consumer_consumer_proto_rawDescGZIP(), []int{4}
}

func (x *CreateNewTopicReq) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type CreateNewTopicRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *common.ReturnMsg `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CreateNewTopicRes) Reset() {
	*x = CreateNewTopicRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_consumer_consumer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNewTopicRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewTopicRes) ProtoMessage() {}

func (x *CreateNewTopicRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_consumer_consumer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewTopicRes.ProtoReflect.Descriptor instead.
func (*CreateNewTopicRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_consumer_consumer_proto_rawDescGZIP(), []int{5}
}

func (x *CreateNewTopicRes) GetResult() *common.ReturnMsg {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetUserRecentBatteryLevelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetUserRecentBatteryLevelReq) Reset() {
	*x = GetUserRecentBatteryLevelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_consumer_consumer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserRecentBatteryLevelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRecentBatteryLevelReq) ProtoMessage() {}

func (x *GetUserRecentBatteryLevelReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_consumer_consumer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRecentBatteryLevelReq.ProtoReflect.Descriptor instead.
func (*GetUserRecentBatteryLevelReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_consumer_consumer_proto_rawDescGZIP(), []int{6}
}

type GetUserRecentBatteryLevelRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetUserRecentBatteryLevelRes) Reset() {
	*x = GetUserRecentBatteryLevelRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_consumer_consumer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserRecentBatteryLevelRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRecentBatteryLevelRes) ProtoMessage() {}

func (x *GetUserRecentBatteryLevelRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_consumer_consumer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRecentBatteryLevelRes.ProtoReflect.Descriptor instead.
func (*GetUserRecentBatteryLevelRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_consumer_consumer_proto_rawDescGZIP(), []int{7}
}

var File_pb_svc_consumer_consumer_proto protoreflect.FileDescriptor

var file_pb_svc_consumer_consumer_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x62, 0x2f, 0x73, 0x76, 0x63, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65,
	0x72, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65,
	0x72, 0x1a, 0x18, 0x70, 0x62, 0x2f, 0x75, 0x6e, 0x69, 0x74, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x22, 0x46, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x75, 0x6e, 0x69,
	0x74, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x4d,
	0x73, 0x67, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x23, 0x0a, 0x0f, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22,
	0x11, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x4d, 0x73, 0x67, 0x52,
	0x65, 0x73, 0x22, 0x29, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x54,
	0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x22, 0x46, 0x0a,
	0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52,
	0x65, 0x73, 0x12, 0x31, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x4d, 0x73, 0x67, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x1e, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x52, 0x65, 0x71, 0x22, 0x1e, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x52, 0x65, 0x73, 0x32, 0xb3, 0x02, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x65, 0x72, 0x12, 0x52, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x4d,
	0x73, 0x67, 0x12, 0x20, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x63, 0x6f, 0x6e, 0x73,
	0x75, 0x6d, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x4d, 0x73,
	0x67, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x63, 0x6f,
	0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x12, 0x58, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4e, 0x65, 0x77, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x22, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76,
	0x63, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4e, 0x65, 0x77, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x70,
	0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x73,
	0x12, 0x79, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x65, 0x6e,
	0x74, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x2d, 0x2e,
	0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x74,
	0x74, 0x65, 0x72, 0x79, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x2d, 0x2e, 0x70,
	0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2e, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x74, 0x74,
	0x65, 0x72, 0x79, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x42, 0x3a, 0x5a, 0x38, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x79, 0x65, 0x6f, 0x6c, 0x2d,
	0x69, 0x2f, 0x62, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2d, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2d,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x76, 0x63, 0x2f, 0x63,
	0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_svc_consumer_consumer_proto_rawDescOnce sync.Once
	file_pb_svc_consumer_consumer_proto_rawDescData = file_pb_svc_consumer_consumer_proto_rawDesc
)

func file_pb_svc_consumer_consumer_proto_rawDescGZIP() []byte {
	file_pb_svc_consumer_consumer_proto_rawDescOnce.Do(func() {
		file_pb_svc_consumer_consumer_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_svc_consumer_consumer_proto_rawDescData)
	})
	return file_pb_svc_consumer_consumer_proto_rawDescData
}

var file_pb_svc_consumer_consumer_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pb_svc_consumer_consumer_proto_goTypes = []interface{}{
	(*GetUserDevicesReq)(nil),            // 0: pb.svc.consumer.GetUserDevicesReq
	(*GetUserDevicesRes)(nil),            // 1: pb.svc.consumer.GetUserDevicesRes
	(*CreateNewMsgReq)(nil),              // 2: pb.svc.consumer.CreateNewMsgReq
	(*CreateNewMsgRes)(nil),              // 3: pb.svc.consumer.CreateNewMsgRes
	(*CreateNewTopicReq)(nil),            // 4: pb.svc.consumer.CreateNewTopicReq
	(*CreateNewTopicRes)(nil),            // 5: pb.svc.consumer.CreateNewTopicRes
	(*GetUserRecentBatteryLevelReq)(nil), // 6: pb.svc.consumer.GetUserRecentBatteryLevelReq
	(*GetUserRecentBatteryLevelRes)(nil), // 7: pb.svc.consumer.GetUserRecentBatteryLevelRes
	(*common.ReturnMsg)(nil),             // 8: pb.unit.common.ReturnMsg
}
var file_pb_svc_consumer_consumer_proto_depIdxs = []int32{
	8, // 0: pb.svc.consumer.GetUserDevicesRes.result:type_name -> pb.unit.common.ReturnMsg
	8, // 1: pb.svc.consumer.CreateNewTopicRes.result:type_name -> pb.unit.common.ReturnMsg
	2, // 2: pb.svc.consumer.Consumer.CreateNewMsg:input_type -> pb.svc.consumer.CreateNewMsgReq
	4, // 3: pb.svc.consumer.Consumer.CreateNewTopic:input_type -> pb.svc.consumer.CreateNewTopicReq
	6, // 4: pb.svc.consumer.Consumer.GetUserRecentBatteryLevel:input_type -> pb.svc.consumer.GetUserRecentBatteryLevelReq
	3, // 5: pb.svc.consumer.Consumer.CreateNewMsg:output_type -> pb.svc.consumer.CreateNewMsgRes
	5, // 6: pb.svc.consumer.Consumer.CreateNewTopic:output_type -> pb.svc.consumer.CreateNewTopicRes
	7, // 7: pb.svc.consumer.Consumer.GetUserRecentBatteryLevel:output_type -> pb.svc.consumer.GetUserRecentBatteryLevelRes
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_svc_consumer_consumer_proto_init() }
func file_pb_svc_consumer_consumer_proto_init() {
	if File_pb_svc_consumer_consumer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_svc_consumer_consumer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserDevicesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_consumer_consumer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserDevicesRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_consumer_consumer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNewMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_consumer_consumer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNewMsgRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_consumer_consumer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNewTopicReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_consumer_consumer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNewTopicRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_consumer_consumer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserRecentBatteryLevelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_consumer_consumer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserRecentBatteryLevelRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_svc_consumer_consumer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_svc_consumer_consumer_proto_goTypes,
		DependencyIndexes: file_pb_svc_consumer_consumer_proto_depIdxs,
		MessageInfos:      file_pb_svc_consumer_consumer_proto_msgTypes,
	}.Build()
	File_pb_svc_consumer_consumer_proto = out.File
	file_pb_svc_consumer_consumer_proto_rawDesc = nil
	file_pb_svc_consumer_consumer_proto_goTypes = nil
	file_pb_svc_consumer_consumer_proto_depIdxs = nil
}
