// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: pb/svc/auth/auth.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *AuthTokenReq) Reset() {
	*x = AuthTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_auth_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTokenReq) ProtoMessage() {}

func (x *AuthTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_auth_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTokenReq.ProtoReflect.Descriptor instead.
func (*AuthTokenReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthTokenRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Code   int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *AuthTokenRes) Reset() {
	*x = AuthTokenRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_auth_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTokenRes) ProtoMessage() {}

func (x *AuthTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_auth_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTokenRes.ProtoReflect.Descriptor instead.
func (*AuthTokenRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthTokenRes) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AuthTokenRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_pb_svc_auth_auth_proto protoreflect.FileDescriptor

var file_pb_svc_auth_auth_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x62, 0x2f, 0x73, 0x76, 0x63, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x61, 0x75,
	0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x22, 0x24, 0x0a, 0x0c, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x3a, 0x0a, 0x0c, 0x41,
	0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x32, 0x49, 0x0a, 0x04, 0x41, 0x75, 0x74, 0x68, 0x12,
	0x41, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x19, 0x2e, 0x70,
	0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x73, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x62, 0x79, 0x65, 0x6f, 0x6c, 0x2d, 0x69, 0x2f, 0x62, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79,
	0x2d, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2d, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2f, 0x70,
	0x62, 0x2f, 0x73, 0x76, 0x63, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pb_svc_auth_auth_proto_rawDescOnce sync.Once
	file_pb_svc_auth_auth_proto_rawDescData = file_pb_svc_auth_auth_proto_rawDesc
)

func file_pb_svc_auth_auth_proto_rawDescGZIP() []byte {
	file_pb_svc_auth_auth_proto_rawDescOnce.Do(func() {
		file_pb_svc_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_svc_auth_auth_proto_rawDescData)
	})
	return file_pb_svc_auth_auth_proto_rawDescData
}

var file_pb_svc_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_svc_auth_auth_proto_goTypes = []interface{}{
	(*AuthTokenReq)(nil), // 0: pb.svc.auth.AuthTokenReq
	(*AuthTokenRes)(nil), // 1: pb.svc.auth.AuthTokenRes
}
var file_pb_svc_auth_auth_proto_depIdxs = []int32{
	0, // 0: pb.svc.auth.Auth.AuthToken:input_type -> pb.svc.auth.AuthTokenReq
	1, // 1: pb.svc.auth.Auth.AuthToken:output_type -> pb.svc.auth.AuthTokenRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_svc_auth_auth_proto_init() }
func file_pb_svc_auth_auth_proto_init() {
	if File_pb_svc_auth_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_svc_auth_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_auth_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthTokenRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_svc_auth_auth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_svc_auth_auth_proto_goTypes,
		DependencyIndexes: file_pb_svc_auth_auth_proto_depIdxs,
		MessageInfos:      file_pb_svc_auth_auth_proto_msgTypes,
	}.Build()
	File_pb_svc_auth_auth_proto = out.File
	file_pb_svc_auth_auth_proto_rawDesc = nil
	file_pb_svc_auth_auth_proto_goTypes = nil
	file_pb_svc_auth_auth_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	AuthToken(ctx context.Context, in *AuthTokenReq, opts ...grpc.CallOption) (*AuthTokenRes, error)
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthClient(cc grpc.ClientConnInterface) AuthClient {
	return &authClient{cc}
}

func (c *authClient) AuthToken(ctx context.Context, in *AuthTokenReq, opts ...grpc.CallOption) (*AuthTokenRes, error) {
	out := new(AuthTokenRes)
	err := c.cc.Invoke(ctx, "/pb.svc.auth.Auth/AuthToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	AuthToken(context.Context, *AuthTokenReq) (*AuthTokenRes, error)
}

// UnimplementedAuthServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (*UnimplementedAuthServer) AuthToken(context.Context, *AuthTokenReq) (*AuthTokenRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthToken not implemented")
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_AuthToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).AuthToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.svc.auth.Auth/AuthToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).AuthToken(ctx, req.(*AuthTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.svc.auth.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthToken",
			Handler:    _Auth_AuthToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/svc/auth/auth.proto",
}
